{
 "metadata": {
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9-final"
  },
  "orig_nbformat": 2,
  "kernelspec": {
   "name": "python3",
   "display_name": "Python 3",
   "language": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2,
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "# from dronekit import connect\n",
    "# vehicle = connect('/dev/ttyACM0', wait_ready=True, baud=115200)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from dronekit import connect, Vehicle\n",
    "\n",
    "class GPSTime:\n",
    "\n",
    "    def __init__(self, gps_time=None, date_time=None):\n",
    "        self.gps_time = gps_time\n",
    "        self.date_time = date_time\n",
    "    \n",
    "    def __str__(self):\n",
    "        return f\"gps_time: {self.gps_time}, date_time: {self.date_time}\"\n",
    "\n",
    "class MyVehicle(Vehicle):\n",
    "    def __init__(self, *args):\n",
    "        super(MyVehicle, self).__init__(*args)\n",
    "\n",
    "        self._datelogger = GPSTime()\n",
    "\n",
    "        # Create a message listener using the decorator.\n",
    "        @self.on_message('SYSTEM_TIME')\n",
    "        def listener(self, name, message):\n",
    "            #print(message)\n",
    "            self._datelogger.gps_time = message.time_unix_usec\n",
    "            self._datelogger.date_time = message.time_unix_usec\n",
    "            self.notify_attribute_listeners('gps_time', self._datelogger)\n",
    "\n",
    "    @property\n",
    "    def gps_time(self):\n",
    "        return self._datelogger"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n"
     ]
    }
   ],
   "source": [
    "import socket\n",
    "\n",
    "try:\n",
    "    vehicle = connect('/dev/ttyACM0', wait_ready=True, baud=115200, vehicle_class=MyVehicle)\n",
    "\n",
    "# Bad TCP connection\n",
    "except socket.error:\n",
    "    print('No server exists!')\n",
    "\n",
    "# Bad TTY connection\n",
    "except exceptions.OSError as e:\n",
    "    print('No serial exists!') \n",
    "\n",
    "# API Error\n",
    "except dronekit.APIException:\n",
    "    print('Timeout!')\n",
    "\n",
    "# Other error\n",
    "except:\n",
    "    print('Some other error!') "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "gps_time: 0, date_time: 0\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n"
     ]
    }
   ],
   "source": [
    "print(vehicle.gps_time)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "# for attribute, value in vehicle.__dict__.items():\n",
    "#     print(attribute, '=', value)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "LocationGlobalRelative:lat=0.0,lon=0.0,alt=3.412\n"
     ]
    }
   ],
   "source": [
    "#\"Latitude, Longtitude, Altitude\"\n",
    "print(vehicle.location.global_relative_frame)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "Attitude:pitch=-0.0011029760353267193,yaw=2.3068463802337646,roll=0.04092269018292427\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n"
     ]
    }
   ],
   "source": [
    "#D4, D5, D6\n",
    "print(vehicle.attitude)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "[-0.08, 0.03, 0.06]"
      ]
     },
     "metadata": {},
     "execution_count": 7
    }
   ],
   "source": [
    "#D1, D2, D3\n",
    "vehicle.velocity"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "Battery:voltage=0.0,current=None,level=None\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n"
     ]
    }
   ],
   "source": [
    "#V, A, BatteryStatus\n",
    "print(vehicle.battery)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "0.0"
      ]
     },
     "metadata": {},
     "execution_count": 9
    }
   ],
   "source": [
    "#AirSpeed\n",
    "vehicle.airspeed"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "0.0848199874162674"
      ]
     },
     "metadata": {},
     "execution_count": 10
    }
   ],
   "source": [
    "#GroundSpeed\n",
    "vehicle.groundspeed"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "'STABILIZE'"
      ]
     },
     "metadata": {},
     "execution_count": 11
    }
   ],
   "source": [
    "'''\n",
    "enum class Number {\n",
    "    STABILIZE =     0,  // manual airframe angle with manual throttle\n",
    "    ACRO =          1,  // manual body-frame angular rate with manual throttle\n",
    "    ALT_HOLD =      2,  // manual airframe angle with automatic throttle\n",
    "    AUTO =          3,  // fully automatic waypoint control using mission commands\n",
    "    GUIDED =        4,  // fully automatic fly to coordinate or fly at velocity/direction using GCS immediate commands\n",
    "    LOITER =        5,  // automatic horizontal acceleration with automatic throttle\n",
    "    RTL =           6,  // automatic return to launching point\n",
    "    CIRCLE =        7,  // automatic circular flight with automatic throttle\n",
    "    LAND =          9,  // automatic landing with horizontal position control\n",
    "    DRIFT =        11,  // semi-automous position, yaw and throttle control\n",
    "    SPORT =        13,  // manual earth-frame angular rate control with manual throttle\n",
    "    FLIP =         14,  // automatically flip the vehicle on the roll axis\n",
    "    AUTOTUNE =     15,  // automatically tune the vehicle's roll and pitch gains\n",
    "    POSHOLD =      16,  // automatic position hold with manual override, with automatic throttle\n",
    "    BRAKE =        17,  // full-brake using inertial/GPS system, no pilot input\n",
    "    THROW =        18,  // throw to launch mode using inertial/GPS system, no pilot input\n",
    "    AVOID_ADSB =   19,  // automatic avoidance of obstacles in the macro scale - e.g. full-sized aircraft\n",
    "    GUIDED_NOGPS = 20,  // guided mode but only accepts attitude and altitude\n",
    "    SMART_RTL =    21,  // SMART_RTL returns to home by retracing its steps\n",
    "    FLOWHOLD  =    22,  // FLOWHOLD holds position with optical flow without rangefinder\n",
    "    FOLLOW    =    23,  // follow attempts to follow another vehicle or ground station\n",
    "    ZIGZAG    =    24,  // ZIGZAG mode is able to fly in a zigzag manner with predefined point A and point B\n",
    "    SYSTEMID  =    25,  // System ID mode produces automated system identification signals in the controllers\n",
    "    AUTOROTATE =   26,  // Autonomous autorotation\n",
    "    NEW_MODE =     27,  // your new flight mode\n",
    "};\n",
    "'''\n",
    "#CurrentFlightMode\n",
    "vehicle.mode.name"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stdout",
     "text": [
      "GPSInfo:fix=1,num_sat=0\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n"
     ]
    }
   ],
   "source": [
    "#GPSStatus\n",
    "print(vehicle.gps_0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "output_type": "execute_result",
     "data": {
      "text/plain": [
       "False"
      ]
     },
     "metadata": {},
     "execution_count": 13
    }
   ],
   "source": [
    "#Motor (report armed/disarmed)\n",
    "vehicle.armed"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "vehicle.close()\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "output_type": "stream",
     "name": "stderr",
     "text": [
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "DroneStatus\n",
      "0\n",
      "1029242\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "DroneStatus\n",
      "0\n",
      "1029244\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "DroneStatus\n",
      "0\n",
      "1029246\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "DroneStatus\n",
      "0\n",
      "1029248\n",
      "DroneStatus\n",
      "0\n",
      "1029250\n",
      "DroneStatus\n",
      "0\n",
      "1029252\n",
      "DroneStatus\n",
      "0\n",
      "1029254\n",
      "DroneStatus\n",
      "0\n",
      "1029256\n",
      "DroneStatus\n",
      "0\n",
      "1029258\n",
      "DroneStatus\n",
      "0\n",
      "1029260\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n",
      "ERROR:dronekit:Exception in message handler for HEARTBEAT\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1531, in notify_message_listeners\n",
      "    fn(self, name, msg)\n",
      "  File \"/home/jetsonv1/.local/lib/python3.6/site-packages/dronekit/__init__.py\", line 1223, in listener\n",
      "    raise APIException(\"mode (%s, %s) not available on mavlink definition\" % (m.custom_mode, m.base_mode))\n",
      "dronekit.APIException: mode (0, 4) not available on mavlink definition\n"
     ]
    }
   ],
   "source": [
    "from kafka import KafkaProducer\n",
    "from kafka.errors import KafkaError\n",
    "import json\n",
    "\n",
    "import time\n",
    "def millis():\n",
    "    return int(round(time.time() * 1000))  \n",
    "\n",
    "def drone_message_dumper(vehicle):\n",
    "    \n",
    "    test_msg = {\n",
    "        'DroneId': '06cdcf5a-0e98-4599-a638-6b17d288e948',\n",
    "        'Latitude': vehicle.location.global_relative_frame.lat,\n",
    "        'Longtitude': vehicle.location.global_relative_frame.lon,\n",
    "        'Altitude': vehicle.location.global_relative_frame.alt,\n",
    "        'D1': vehicle.velocity[0],\n",
    "        'D2': vehicle.velocity[1],\n",
    "        'D3': vehicle.velocity[2],\n",
    "        'D4': vehicle.attitude.pitch,\n",
    "        'D5': vehicle.attitude.yaw,\n",
    "        'D6': vehicle.attitude.roll,\n",
    "        'V': vehicle.battery.voltage,\n",
    "        'A': vehicle.battery.current,\n",
    "        'AirSpeed': vehicle.airspeed,\n",
    "        'GroundSpeed': vehicle.groundspeed,\n",
    "        'TeleQuality': 0,\n",
    "        'GPSTime': '12:45:01',\n",
    "        'GPSStatus': 1,\n",
    "        'BatteryStatus': 0.0,\n",
    "        'CurrentWaypointNumber': 1,\n",
    "        'DistanceToWaypoint': 25.5,\n",
    "        'CurrentFlightMode': '0',\n",
    "        'DataTime': str(millis()),\n",
    "        'Motor': 'disarmed',\n",
    "    }\n",
    "\n",
    "    return test_msg\n",
    "\n",
    "producer = KafkaProducer(bootstrap_servers='mdrone.southeastasia.cloudapp.azure.com:9092',value_serializer=lambda m: json.dumps(m).encode('ascii'))\n",
    "# future = producer.send('DroneStatus', {'test':'yaya'})\n",
    "def on_send_success(record_metadata):\n",
    "    print(record_metadata.topic)\n",
    "    print(record_metadata.partition)\n",
    "    print(record_metadata.offset)\n",
    "\n",
    "def on_send_error(excp):\n",
    "    log.error('I am an errback', exc_info=excp)\n",
    "    # handle exception\n",
    "for _ in range(10):\n",
    "    producer.send('DroneStatus',drone_message_dumper(vehicle)).add_callback(on_send_success).add_errback(on_send_error)\n",
    "    time.sleep(1.0)\n",
    "producer.flush()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "output_type": "error",
     "ename": "AttributeError",
     "evalue": "'GPSInfo' object has no attribute 'fix'",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-16-f1a39eeaa03b>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mvehicle\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgps_0\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfix\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m: 'GPSInfo' object has no attribute 'fix'"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "vehicle.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ]
}